### ISSUE TITLE
New Error loading WAR Base

### ISSUE THREAD

**Issue by netquik** [Sigma582/SWC.Tools#10]
Since a while i get this error trying to load WAR BASE

2018-09-17 13:00:19 | ERROR: SWC.Tools.Common.Networking.Exception.StatusException: The server returned Status code 2400
   in SWC.Tools.Common.Networking.MessageManager.Send[TResult](Message message, Int32 retryCount)
   in SWC.Tools.Common.Networking.MessageManager.Send[TResult](Message message)
   in SWC.Tools.Common.Networking.MessageManager.UpdateWarLayout(Dictionary`2 positions)
   in SWC.Tools.LayoutManager.ViewModels.MainViewModel.Load(Object arg)

**Comment by xeno6696** [comment]
I get 2420, but same exact problem.

**Comment by xeno6696** [comment]
```
2018-10-10 12:41:08 | ERROR: SWC.Tools.Common.Networking.Exception.StatusException: The server returned Status code 2420
   at SWC.Tools.Common.Networking.MessageManager.Send[TResult](Message message, Int32 retryCount)
   at SWC.Tools.Common.Networking.MessageManager.Send[TResult](Message message)
   at SWC.Tools.Common.Networking.MessageManager.UpdateWarLayout(Dictionary`2 positions)
   at SWC.Tools.LayoutManager.ViewModels.MainViewModel.Load(Object arg)
```

**Comment by xeno6696** [comment]
2420 is that you have debris in your pvp base that won't let you save your war base.
