### ISSUE TITLE
Layout Manager login fails since Server Update

### ISSUE THREAD

**Issue by darrenjj** [Sigma582/SWC.Tools#7]
Since the backend server update we now get this error message on login. I've checked that the IP address is still valid, and it seems to be, it still resolves to - n7-starts-web-active.playdom.com, so i'm guessing they may have changed the path

2017-09-15 14:44:47 | ERROR: System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 35.193.202.54:443
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SWC.Tools.Common.Networking.MessageSender.<SendInternal>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at SWC.Tools.Common.Networking.MessageSender.Send(Message message)
   at SWC.Tools.Common.Networking.MessageManager.GetAuthToken()
   at SWC.Tools.Common.Networking.MessageManager.Init()
   at SWC.Tools.Common.Networking.MessageManager.Refresh()
   at SWC.Tools.LayoutManager.ViewModels.MainViewModel.Login(Object arg)
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 35.193.202.54:443
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SWC.Tools.Common.Networking.MessageSender.<SendInternal>d__4.MoveNext()<---

**Comment by ghost** [comment]
I am getting an error, although the error log is different than yours. I updated to the latest version of Layout Manager and verified my Player ID and Player Special.
Here's my error text:

2017-09-16 15:00:16 | ERROR: System.Runtime.Serialization.SerializationException: Expecting element 'root' from namespace ''.. Encountered 'None'  with name '', namespace ''. 
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   at System.Runtime.Serialization.XmlObjectSerializer.InternalReadObject(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(Stream stream)
   at SWC.Tools.Common.Networking.MessageManager.GetAuthToken()
   at SWC.Tools.Common.Networking.MessageManager.Init()
   at SWC.Tools.Common.Networking.MessageManager.Refresh()
   at SWC.Tools.LayoutManager.ViewModels.MainViewModel.Login(Object arg)
![tt2 error layout manager](https://user-images.githubusercontent.com/32021978/30515175-07830f00-9af1-11e7-8198-f116dac37385.PNG)

**Comment by Sigma582** [comment]
fixed in 1.4
