### ISSUE TITLE
I can no longer login after SWC Server Maintenance Done on 10/25/2017

### ISSUE THREAD

**Issue by BeowulfPkr** [Sigma582/SWC.Tools#9]
I can no longer login with layout manager after SWC Server Maintenance Done on 10/25/2017?

**Comment by Ryesistance** [comment]
Also experiencing issues.

2017-10-26 08:12:04 | ERROR: System.Runtime.Serialization.SerializationException: There was an error deserializing the object of type SWC.Tools.Common.Networking.Json.Responses.Response`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]. Encountered unexpected character '<'. ---> System.Xml.XmlException: Encountered unexpected character '<'.

**Comment by BeowulfPkr** [comment]
2017-10-26 08:02:25 | ERROR: System.Runtime.Serialization.SerializationException: There was an error deserializing the object of type SWC.Tools.Common.Networking.Json.Responses.Response`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]. Encountered unexpected character '<'. ---> System.Xml.XmlException: Encountered unexpected character '<'.
   at System.Xml.XmlExceptionHelper.ThrowXmlException(XmlDictionaryReader reader, XmlException exception)
   at System.Runtime.Serialization.Json.XmlJsonReader.ReadAttributes()
   at System.Runtime.Serialization.Json.XmlJsonReader.ReadNonExistentElementName(StringHandleConstStringType elementName)
   at System.Runtime.Serialization.Json.XmlJsonReader.Read()
   at System.Xml.XmlBaseReader.IsStartElement()
   at System.Xml.XmlBaseReader.IsStartElement(XmlDictionaryString localName, XmlDictionaryString namespaceUri)
   at System.Runtime.Serialization.XmlReaderDelegator.IsStartElement(XmlDictionaryString localname, XmlDictionaryString ns)
   at System.Runtime.Serialization.XmlObjectSerializer.IsRootElement(XmlReaderDelegator reader, DataContract contract, XmlDictionaryString name, XmlDictionaryString ns)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalIsStartObject(XmlReaderDelegator reader)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   at System.Runtime.Serialization.XmlObjectSerializer.InternalReadObject(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   --- End of inner exception stack trace ---
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(Stream stream)
   at SWC.Tools.Common.Networking.MessageManager.GetAuthToken()
   at SWC.Tools.Common.Networking.MessageManager.Init()
   at SWC.Tools.Common.Networking.MessageManager.Refresh()
   at SWC.Tools.LayoutManager.ViewModels.MainViewModel.Login(Object arg)

**Comment by spacesareevil** [comment]
Change value of "androidServerUrl" in SWC.Tools.LayoutManager.exe.Config to "https://starts-app-prod.disney.io/starts/batch/json" to get Layout Manager to work again.

**Comment by BeowulfPkr** [comment]
Thanks that fixed it!  In my case I did not even have that key so I add to add this:

`<add key="androidServerUrl" value="https://starts-app-prod.disney.io/starts/batch/json" />`
